### PR TITLE
Add syntax highlighting queries

### PR DESCRIPTION
**Pull request by Wilfred**
Add highlighting for literals, constants and operators.

### CODE REVIEW

**Comment by sogaiu** [comment]
Hi @Wilfred

My understanding is that the highlighting queries are (tend to be?) editor-specific.

For example, in Neovim's case, some highlighting queries for clojure live in the nvim-treesitter repository: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/clojure/highlights.scm

In the case of Emacs, when I conversed with some Cider / clojure-mode folks, I got the sense there wasn't much interest, so I didn't make an attempt to get tree-sitter-clojure or highlighting queries I had made added to https://github.com/emacs-tree-sitter/tree-sitter-langs.

I had been assuming that each relevant editor would end up with its own set of highlighting queries that would get maintained at the relevant repositories.  But perhaps there is some other use you have in mind for the queries you made?

**Comment by Wilfred** [comment]
Hi @sogaiu, great question!

I'm using tree-sitter-clojure with my [difftastic](https://github.com/wilfred/difftastic) project, which is a diff tool rather than an editor. Almost all the tree-sitter parsers I'm using ship with a highlights.scm.

The queries are pretty generic: e.g. `(str_lit) @string` is something that any tool would want I think.

It looks to me like Neovim is extending the queries.scm files with additional syntax. For example the `#lua-match?` query is specific to neovim I think.

The neovim highlights are being contributed upstream though. For example, https://github.com/nvim-treesitter/nvim-treesitter/pull/2290 was also submitted to tree-sitter-java.

Having this file would mean any tree-sitter-clojure user gets decent highlighting without any extra effort, which seems worthwhile :)

**Comment by sogaiu** [comment]
@Wilfred Thanks for the detailed explanation.

It's a good point that having some simple default could be beneficial for tool use cases.  Along those lines, I had forgotten about the `highlight` subcommand that tree-sitter provides as I had not succeeded in getting it to work previously.

So I think adding some `queries/highlights.scm` file makes sense but I am unsure about how things will and should behave for `comment`.  I happen to use `comment` blocks to record code usages / tests, and very much prefer that content within be highlighted similarly to code outside of `comment` blocks.  I still need to investigate a bit regarding this -- as I've only just managed to get the `highlight` subcommand to function.

I noticed the `queries/highlights.scm` file in this PR has `(comment) @comment` in it.  If that were not there, would that make a difference for difftastic?

Also I wonder a bit about the future -- specifically, if there seems to be a good reason to change `highlights.scm` down the line (say, something that comes about from some non-difftastic use case), could that be an issue for difftastic?

I haven't tried difftastic yet (my rust version is too old it seems), but hope to before too long :)

**Comment by Wilfred** [comment]
> I happen to use comment blocks to record code usages / tests, and very much prefer that content within be highlighted similarly to code outside of comment blocks.

Not to worry -- those forms aren't affected. `(comment) @comment` means "apply the @comment tag to tree-sitter nodes called 'comment'". This won't affect things like `(comment (+ 1 2))` as the tree-sitter node is `list_lit`.

>  If that were not there, would that make a difference for difftastic?

FWIW it's not necessary for difftastic: I treat tree-sitter nodes marked 'extra' or nodes explicitly named 'comment' as comments regardless.

> if there seems to be a good reason to change highlights.scm down the line (say, something that comes about from some non-difftastic use case), could that be an issue for difftastic?

Not at all :)

Difftastic just uses any occurrences of `@string`, `@operator` and so on for highlighting. Any more exotic highlighting won't affect it, and it'll cope fine if you remove anything too.

**Comment by sogaiu** [comment]
> Not to worry -- those forms aren't affected. `(comment) @comment` means "apply the @comment tag to tree-sitter nodes called 'comment'". This won't affect things like `(comment (+ 1 2))` as the tree-sitter node is `list_lit`.

Oh right -- I guess I misinterpreted :)

Thanks for the explanation.

**Pull request merged**
