### PR TITLE
Upgrade to tree-sitter 0.19.1

### PR DESCRIPTION
**Pull request by nwjsmith**
Tree sitter 0.19.0 broke ABI compatibility, and new parsers need to be generated for compatibility. This upgrades the tree-sitter dependency and regenerates the bindings, including a new Rust binding.

### CODE REVIEW

**Comment by sogaiu** [comment]
Thanks!

I have been observing problems mentioned / disccused with the most recent series of releases and so have been holding off on upgrading.

I am not yet sure it's a good time to upgrade.

**Comment by sogaiu** [comment]
It looks like 0.19.2 was released: https://github.com/tree-sitter/tree-sitter/releases/tag/v0.19.2

My current thinking is to wait for things to settle a bit.

Please let me know if that seems to be a problem.

**Comment by sogaiu** [comment]
Here's my work-in-progress branch related to this: https://github.com/sogaiu/tree-sitter-clojure/tree/upgrade-to-ts-0.19.x

**Comment by nwjsmith** [comment]
@sogaiu this all sounds good to me! Thanks for your work on this

**Pull request closed without merging**
