### PR TITLE
Ignore generated files.

### PR DESCRIPTION
**Pull request by borkdude**

### CODE REVIEW

**Comment by sogaiu** [comment]
It turns out that if one implements something using `externals`, it's necessary to add a file `scanner.c` (or .cc) under `src` and update `binding.gyp` to contain a reference to the scanner source file.

There's a version of the grammar in [an earlier commit](https://github.com/sogaiu/tree-sitter-clojure/commit/319eae813b29621cdbefe9750d558e4b1634f7b2) that does this and I'm not yet confident that there won't be a need for some externals at some point.

Thoughts?

**Comment by borkdude** [comment]
@sogaiu The problem that this commit solves for me is that my submodule directory doesn't get dirty, and git won't complain that I should commit something. Any other approach that solves that problem is fine with me.

**Comment by borkdude** [comment]
Example of what I'm seeing in analyze-reify after running script/tree-sitter-clojure:

```
$ git st
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	modified:   tree-sitter-clojure (new commits, untracked content)

no changes added to commit (use "git add" and/or "git commit -a")
```

In the submodule:
```
$ git st
On branch gitignore
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	binding.gyp
	src/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by sogaiu** [comment]
Seems like odd behavior on git's part, but I'll go ahead and merge the changes for the moment.

**Comment by sogaiu** [comment]
Note that currently these files are back (and have been back for a while).

AFAIU, it's generally how many tree-sitter grammar repositories currently do things.

Multiple programs (e.g. nvim-treesitter and Emacs 29+) that use the grammars use the generated source that is fetched.  Although some of them do have the ability to generate a grammar's `.c` source, this requires the presence of an appropriate tree-sitter cli on the user's machine.  At this point in time (and perhaps forever?) it doesn't seem reasonable to assume an end user will have the tree-sitter cli installed on their machine.

The issue of having the generated files in a grammar repository is touched on a bit [here](https://github.com/tree-sitter/tree-sitter/issues/930).   So things might change along those lines at some point.

**Pull request merged**
