### PR TITLE
Update tree sitter

### PR DESCRIPTION
**Pull request by prcastro**
In order to make it work with Zed editor (https://github.com/zed-industries/zed/pull/6988)

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
I believe this will be handled (see #57).

**Comment by prcastro** [comment]
Are we planning on removing the Rust bindings? I was kinda relying on it for Zed.

**Comment by sogaiu** [comment]
The [current plan is to be removing bindings](https://github.com/sogaiu/tree-sitter-clojure/blob/6e41628e9d18b19caea1cb1d72aae4ccff5bdfe9/doc/what-and-why.md#about-the-bindings):

> The bindings are not tested in any way and only really exist as a side-effect of running the tree-sitter cli's generate subcommand. They may be removed at some point, but they should be straight-forward to generate as long as one has a suitable tree-sitter cli and the grammar.js file mentioned above, but see below for details and/or have a look at some [official docs](https://github.com/tree-sitter/tree-sitter/blob/master/docs/section-3-creating-parsers.md#command-generate).

**Comment by sogaiu** [comment]
Not sure what Zed requires at this point, but FWIW, there is now a tagged release v0.0.13 that [has a generated parser at API 14](https://github.com/sogaiu/tree-sitter-clojure/commit/21b2f8879b380dc10c4336cf47cce828a8499279).

Going to close this PR for now, but feel free to open an issue or otherwise communicate if needed :)

**Pull request closed without merging**
